import { timingSafeEqual } from "node:crypto";
import type { Request, Response } from "express";
import { createIdea, createVideoFromIdea, decideVideoApproval, getDashboardSnapshot, getProjectById, getVideoWorkflowStatus, listPendingVideoApprovals, listProjectIdeas, listProjectJobs, listProjectProviders, listProjectSchedules, listProjectVideos, prepareNarrationJob, setProjectAutomationMode } from "./repository";
import { syncChannelAnalytics } from "./youtube-analytics";
import { suggestGrowthExperiments } from "./growth-intelligence";
import { enqueueJob } from "./queue";
import { executePipelineInitializeJob } from "./worker";
import { runDueJobsManually } from "./worker";
import { setElevenLabsVoiceId } from "./repository";

type TelegramApiResponse<T> = { ok: boolean; result?: T; description?: string };
type TelegramUpdate = { message?: { chat: { id: number }; from?: { id: number }; text?: string }; callback_query?: { id: string; from: { id: number }; message?: { chat: { id: number } }; data?: string } };
const TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const OWNER_ID = process.env.TELEGRAM_OWNER_USER_ID;
const WEBHOOK_SECRET = process.env.TELEGRAM_WEBHOOK_SECRET;

function requireTelegramConfig() { if (!TOKEN || !OWNER_ID || !WEBHOOK_SECRET) throw new Error("Telegram غير مهيأ بعد."); return { token: TOKEN }; }
async function telegramRequest<T>(method: string, body: Record<string, unknown>): Promise<T> { const { token } = requireTelegramConfig(); const response = await fetch(`https://api.telegram.org/bot${token}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = (await response.json()) as TelegramApiResponse<T>; if (!response.ok || !payload.ok || !payload.result) throw new Error(payload.description ?? `Telegram ${method} failed.`); return payload.result; }
export async function verifyTelegramBot() { return telegramRequest<{ id: number; username?: string; first_name: string }>("getMe", {}); }
export function isAllowedTelegramOwner(userId: number | string | undefined) { return Boolean(userId && OWNER_ID && String(userId) === OWNER_ID); }
export function hasValidTelegramWebhookSecret(value: string | undefined) { if (!value || !WEBHOOK_SECRET || value.length !== WEBHOOK_SECRET.length) return false; return timingSafeEqual(Buffer.from(value), Buffer.from(WEBHOOK_SECRET)); }

function mainKeyboard() { return { inline_keyboard: [[{ text: "إنشاء فيديو", callback_data: "create_video" }, { text: "الأفكار", callback_data: "ideas" }], [{ text: "المشاريع", callback_data: "projects" }, { text: "الطابور", callback_data: "queue" }], [{ text: "تشغيل الدفعة", callback_data: "run_queue" }, { text: "المعاينة", callback_data: "preview" }], [{ text: "التحليلات", callback_data: "analytics" }, { text: "YouTube", callback_data: "youtube" }], [{ text: "الجدولة", callback_data: "scheduler" }, { text: "الإعدادات", callback_data: "settings" }], [{ text: "المزودون", callback_data: "providers" }, { text: "صحة النظام", callback_data: "health" }], [{ text: "وضع الأتمتة", callback_data: "automation_mode" }]] }; }
function automationKeyboard(target?: "semi_auto" | "conditional_auto") { return target ? { inline_keyboard: [[{ text: "تأكيد تغيير الوضع", callback_data: `confirm_mode:${target}` }, { text: "إلغاء", callback_data: "dashboard" }]] } : { inline_keyboard: [[{ text: "Full Review", callback_data: "confirm_mode:full_review" }], [{ text: "Semi Auto", callback_data: "request_mode:semi_auto" }], [{ text: "Conditional Auto", callback_data: "request_mode:conditional_auto" }]] }; }
async function sendMessage(chatId: number, text: string, replyMarkup?: Record<string, unknown>) { return telegramRequest("sendMessage", { chat_id: chatId, text, parse_mode: "HTML", reply_markup: replyMarkup }); }
async function answerCallbackQuery(callbackQueryId: string) { return telegramRequest("answerCallbackQuery", { callback_query_id: callbackQueryId }); }
async function renderDashboard(chatId: number, projectId: number) { const [snapshot, project] = await Promise.all([getDashboardSnapshot(projectId), getProjectById(projectId)]); const jobCount = Object.values(snapshot.jobStatusCounts).reduce((sum, value) => sum + Number(value), 0); return sendMessage(chatId, ["<b>نُسغ — مركز التحكم</b>", `الوضع: <b>${project?.automationMode ?? "full_review"}</b>`, `مشاريع الفيديو: <b>${snapshot.latestVideos.length}</b>`, `الطابور: <b>${jobCount}</b>`, `المزودون المهيأون: <b>${snapshot.providerRows.filter(provider => provider.isEnabled).length}</b>`, "\nكل نشر يتطلب اعتمادًا بشريًا صريحًا."].join("\n"), mainKeyboard()); }
export async function sendVideoApprovalRequest(chatId: number, input: { videoId: number; title: string; qualityScore?: number | null; approvalType?: "idea" | "final_video" }) { const approvalType = input.approvalType ?? "final_video"; const label = approvalType === "idea" ? "مراجعة الفكرة" : "مراجعة الفيديو النهائي"; return sendMessage(chatId, `<b>${label} #${input.videoId}</b>\n${input.title}\nدرجة الجودة: <b>${input.qualityScore ?? "غير مكتملة"}</b>\n\nلا ينتقل المسار التالي قبل اعتمادك.`, { inline_keyboard: [[{ text: "اعتماد", callback_data: `review:${approvalType}:approve:${input.videoId}` }, { text: "رفض", callback_data: `review:${approvalType}:reject:${input.videoId}` }, { text: "إعادة توليد", callback_data: `review:${approvalType}:regenerate:${input.videoId}` }]] }); }

export function createTelegramWebhookHandler(projectIdProvider: () => Promise<number>) { return async (req: Request, res: Response) => { try { if (!hasValidTelegramWebhookSecret(req.header("x-telegram-bot-api-secret-token"))) return res.status(401).json({ ok: false, error: "invalid_webhook_secret" }); const update = req.body as TelegramUpdate; const actorId = update.callback_query?.from.id ?? update.message?.from?.id; const chatId = update.callback_query?.message?.chat.id ?? update.message?.chat.id; if (!isAllowedTelegramOwner(actorId) || !chatId) return res.status(403).json({ ok: false, error: "owner_only" }); const projectId = await projectIdProvider(); const command = update.message?.text?.trim(); const callback = update.callback_query?.data; if (update.callback_query) await answerCallbackQuery(update.callback_query.id);
      if (command?.startsWith("/new ")) { const raw = command.slice(5); const [rawFormat, title, centralIdea] = raw.split("|").map(part => part?.trim()); const format = rawFormat === "short" ? "short" : rawFormat === "long" ? "long_form" : null; if (!format || !title || !centralIdea || centralIdea.length < 30) await sendMessage(chatId, "صيغة الإنشاء: <code>/new short | العنوان | الفكرة المركزية</code>\nأو <code>/new long | العنوان | الفكرة المركزية</code>.", mainKeyboard()); else { const idea = await createIdea({ projectId, title, centralIdea, contentPillar: "Everyday Psychology & Hidden Behavior", targetFormat: format }); if (!idea) throw new Error("تعذر إنشاء الفكرة."); const video = await createVideoFromIdea({ projectId, ideaId: idea.id, title, videoType: format, targetDurationSeconds: format === "short" ? 55 : 480 }); if (!video) throw new Error("تعذر إنشاء مشروع الفيديو."); const job = await enqueueJob({ projectId, videoId: video.id, jobType: "pipeline.initialize", payload: { stage: "idea", videoId: video.id, initiatedBy: "telegram" } }); const initialReview = await executePipelineInitializeJob(job.id); await sendMessage(chatId, initialReview.state === "requires_review" ? `تم إنشاء فيديو #${video.id}. ينتظر الآن اعتماد الفكرة قبل البحث والإنتاج.` : `تم إنشاء فيديو #${video.id} لكن تعذر وضعه في مراجعة الفكرة؛ راجع الطابور.`, mainKeyboard()); } }
      else if (command?.startsWith("/voice ")) { const voiceId = command.slice(7).trim(); await setElevenLabsVoiceId(projectId, voiceId); await sendMessage(chatId, "تم حفظ Voice ID للراوي الثابت. سيظل كل توليد صوت خاضعًا لمراجعة الحقوق والحصة قبل الرندر.", mainKeyboard()); }
      else if (command?.startsWith("/tts ")) { const videoId = Number(command.slice(5).trim()); if (!Number.isSafeInteger(videoId) || videoId <= 0) await sendMessage(chatId, "صيغة التشغيل: <code>/tts رقم_الفيديو</code>. لا يبدأ الصوت إلا من سكريبت معتمد وVoice ID محفوظ.", mainKeyboard()); else { const prepared = await prepareNarrationJob({ projectId, videoId, requestedBy: "telegram_control_center" }); await sendMessage(chatId, prepared.duplicate ? `توجد بالفعل مهمة صوت للفيديو #${videoId} بحالة <b>${prepared.job.status}</b>. لن ننشئ مهمة مكررة.` : `أضيف صوت الفيديو #${videoId} إلى الطابور من سكريبت معتمد (${prepared.narrationLength} حرفًا). استخدم <code>/run</code> للتشغيل؛ سيبقى الناتج للمراجعة البشرية.`, mainKeyboard()); } }
      else if (command === "/start" || command === "/dashboard" || callback === "dashboard") await renderDashboard(chatId, projectId);
      else if (callback === "create_video") await sendMessage(chatId, "أنشئ فيديو فعليًا بهذه الصيغة:\n<code>/new short | العنوان | الفكرة المركزية</code>\nأو\n<code>/new long | العنوان | الفكرة المركزية</code>", mainKeyboard());
      else if (callback === "ideas") { const rows = await listProjectIdeas(projectId); await sendMessage(chatId, rows.length ? `<b>الأفكار</b>\n${rows.map(idea => `• #${idea.id} — ${idea.title} — <b>${idea.status}</b>`).join("\n")}` : "<b>الأفكار</b>\nلا توجد أفكار محفوظة بعد.", mainKeyboard()); }
      else if (callback === "projects") { const rows = await listProjectVideos(projectId); await sendMessage(chatId, rows.length ? `<b>مشاريع الفيديو</b>\n${rows.slice(0, 10).map(video => `• #${video.id} — ${video.title} — <b>${video.status}</b>`).join("\n")}` : "<b>مشاريع الفيديو</b>\nلا يوجد مشروع فيديو بعد.", rows.length ? { inline_keyboard: [...rows.slice(0, 6).map(video => [{ text: `حالة #${video.id}`, callback_data: `video_status:${video.id}` }]), ...mainKeyboard().inline_keyboard] } : mainKeyboard()); }
      else if (command === "/queue" || callback === "queue") { const rows = await listProjectJobs(projectId); await sendMessage(chatId, rows.length ? `<b>الطابور</b>\n${rows.slice(0, 8).map(job => `• #${job.id} — ${job.jobType} — <b>${job.status}</b>`).join("\n")}` : "<b>الطابور</b>\nلا توجد وظائف بعد.", mainKeyboard()); }
      else if (callback === "run_queue" || command === "/run") { const execution = await runDueJobsManually(projectId, 5); await sendMessage(chatId, execution.scanned ? `<b>تشغيل الدفعة</b>\nتمت معالجة ${execution.scanned} مهمة: ${execution.outcomes.map(row => `#${row.jobId} → ${row.state}`).join("، ")}` : "<b>تشغيل الدفعة</b>\nلا توجد مهام مستحقة للتشغيل الآن.", mainKeyboard()); }
      else if (callback === "health" || command === "/health" || callback === "providers") { const rows = await listProjectProviders(projectId); await sendMessage(chatId, rows.length ? `<b>المزودون</b>\n${rows.map(provider => `• ${provider.displayName} (${provider.providerType}) — <b>${provider.status}</b>`).join("\n")}` : "<b>المزودون</b>\nلا يوجد مزود مسجل بعد.", mainKeyboard()); }
      else if (callback === "preview" || command === "/reviews") { const pending = await listPendingVideoApprovals(projectId); if (!pending.length) await sendMessage(chatId, "<b>المراجعات</b>\nلا توجد مراجعات معلقة الآن.", mainKeyboard()); else await sendMessage(chatId, `<b>المراجعات المعلقة (${pending.length})</b>\n${pending.map(item => `• #${item.videoId} — ${item.title} — <b>${item.approvalType}</b> — ${item.videoStatus}`).join("\n")}`, { inline_keyboard: [...pending.slice(0, 8).map(item => [{ text: `فتح مراجعة #${item.videoId}`, callback_data: `open_review:${item.approvalType}:${item.videoId}` }]), ...mainKeyboard().inline_keyboard] }); }
      else if (callback === "scheduler") { const rows = await listProjectSchedules(projectId); await sendMessage(chatId, rows.length ? `<b>الجدولة</b>\n${rows.map(schedule => `• ${schedule.name} — <b>${schedule.isEnabled ? "مفعلة" : "متوقفة"}</b>`).join("\n")}` : "<b>الجدولة</b>\nلا توجد مهمة دورية مفعلة. لن تُنشأ جدولة قبل نشر التطبيق وتهيئة Heartbeat.", mainKeyboard()); }
      else if (callback === "settings") { const project = await getProjectById(projectId); await sendMessage(chatId, `<b>الإعدادات النشطة</b>\nاللغة: العربية\nالمنطقة الزمنية: ${project?.timezone ?? "Africa/Cairo"}\nالأتمتة: <b>${project?.automationMode ?? "full_review"}</b>\nالموسيقى: <b>OFF</b>`, mainKeyboard()); }
      else if (callback === "youtube") await sendMessage(chatId, "<b>YouTube</b>\nالقناة متصلة عبر OAuth خادمي مشفر. الرفع والنشر ما زالا مقيدين بالمراجعة البشرية الصريحة.", mainKeyboard());
      else if (callback === "analytics" || command === "/analytics") {
        try {
          const report = await syncChannelAnalytics(projectId, 28);
          const recommendations = suggestGrowthExperiments(report.metrics).slice(0, 3);
          await sendMessage(chatId, [`<b>تحليلات YouTube — آخر 28 يومًا</b>`, `المشاهدات: <b>${report.metrics.views}</b>`, `وقت المشاهدة بالدقائق: <b>${report.metrics.watchTimeMinutes}</b>`, `متوسط مدة المشاهدة: <b>${report.metrics.averageViewDurationSeconds}ث</b>`, `مشتركون مكتسبون: <b>${report.metrics.subscribersGained}</b>`, `الإعجابات: <b>${report.metrics.likes}</b>`, recommendations.length ? `\n<b>اقتراحات للمراجعة</b>\n${recommendations.map(item => `• ${item.suggestion}`).join("\n")}` : "", "\nهذه توصيات فقط؛ لا تغير تلقائيًا قواعد المحتوى أو النشر."].filter(Boolean).join("\n"), mainKeyboard());
        } catch (analyticsError) {
          await sendMessage(chatId, `<b>تعذر تحديث التحليلات الآن</b>\n${analyticsError instanceof Error ? analyticsError.message : "خطأ غير معروف"}\nلن يؤثر ذلك في وضع المراجعة أو النشر.`, mainKeyboard());
        }
      }
      else if (callback === "automation_mode" || command === "/automation") await sendMessage(chatId, "<b>تغيير وضع الأتمتة</b>\nالمراجعة الكاملة هي الوضع الافتراضي. تتطلب الأوضاع الأعلى تأكيدًا إضافيًا، ولا تتجاوز أعلام السلامة والمراجعة البشرية.", automationKeyboard());
      else if (callback?.startsWith("request_mode:")) { const target = callback.split(":")[1] as "semi_auto" | "conditional_auto"; await sendMessage(chatId, `أنت على وشك تفعيل <b>${target}</b>. سيظل أي فشل للسلامة أو التحقق أو الحقوق أو الجودة متوقفًا للمراجعة البشرية.`, automationKeyboard(target)); }
      else if (callback?.startsWith("confirm_mode:")) { const target = callback.split(":")[1] as "full_review" | "semi_auto" | "conditional_auto"; const project = await setProjectAutomationMode(projectId, target); await sendMessage(chatId, `تم تغيير وضع الأتمتة إلى <b>${project?.automationMode ?? target}</b>.`, mainKeyboard()); }
      else if (callback?.startsWith("video_status:") || command?.startsWith("/status ")) { const rawVideoId = callback?.split(":")[1] ?? command?.slice(8).trim(); const videoId = Number(rawVideoId); if (!Number.isSafeInteger(videoId) || videoId <= 0) await sendMessage(chatId, "صيغة الحالة: <code>/status رقم_الفيديو</code>.", mainKeyboard()); else { const status = await getVideoWorkflowStatus(projectId, videoId); const latestJob = status.latestJobs[0]; const audio = status.tracks[0]; await sendMessage(chatId, ["<b>حالة الفيديو #" + status.video.id + "</b>", status.video.title, `الحالة: <b>${status.video.status}</b>`, `المراجعات المعلقة: <b>${status.pendingApprovals.map(item => item.approvalType).join("، ") || "لا يوجد"}</b>`, `آخر وظيفة: <b>${latestJob ? `${latestJob.jobType} — ${latestJob.status}` : "لا توجد"}</b>`, `الصوت: <b>${audio ? `${audio.audioType} — ${audio.reviewStatus}` : "غير مولّد"}</b>`, status.video.safetyFlags?.length ? `أعلام السلامة: <b>${status.video.safetyFlags.join("، ")}</b>` : "أعلام السلامة: <b>لا يوجد</b>", "\nاستخدم <code>/tts رقم_الفيديو</code> فقط بعد اعتماد السكريبت وتهيئة Voice ID."].join("\n"), mainKeyboard()); } }
      else if (callback?.startsWith("open_review:")) { const [, approvalType, rawVideoId] = callback.split(":"); const videoId = Number(rawVideoId); const pending = await listPendingVideoApprovals(projectId); const review = pending.find(item => item.videoId === videoId && item.approvalType === approvalType); if (!review) throw new Error("طلب المراجعة لم يعد معلقًا أو لا يطابق المرحلة المطلوبة."); await sendVideoApprovalRequest(chatId, { videoId: review.videoId, title: review.title, qualityScore: review.qualityScore, approvalType: review.approvalType === "idea" ? "idea" : "final_video" }); }
      else if (callback?.startsWith("review:")) { const parts = callback.split(":"); const hasStage = parts.length === 4; const approvalType = hasStage ? parts[1] as "idea" | "final_video" : "final_video"; const action = hasStage ? parts[2] : parts[1]; const rawVideoId = hasStage ? parts[3] : parts[2]; const videoId = Number(rawVideoId); if (!Number.isSafeInteger(videoId) || !["idea", "final_video"].includes(approvalType)) throw new Error("معرف أو مرحلة مراجعة غير صالحين."); const decision = action === "approve" ? "approved" : action === "reject" ? "rejected" : "requires_changes"; await decideVideoApproval({ projectId, videoId, decision, approvalType }); await sendMessage(chatId, decision === "approved" ? (approvalType === "idea" ? "تم اعتماد الفكرة. يمكن الآن الانتقال إلى البحث بعد إنشاء المهمة المناسبة." : "تم اعتماد الفيديو النهائي.") : decision === "rejected" ? "تم رفض المراجعة." : "سُجل طلب إعادة التوليد. لم يبدأ النظام إنشاءًا تلقائيًا؛ يجب إنشاء المهمة المناسبة بعد مراجعة التعديل.", mainKeyboard()); }
      else await sendMessage(chatId, "الأمر غير معروف. استخدم /dashboard للعودة إلى مركز التحكم.", mainKeyboard());
      return res.status(200).json({ ok: true });
    } catch (error) { return res.status(500).json({ ok: false, error: error instanceof Error ? error.message : "telegram_webhook_failed" }); } }; }
